apiVersion: apps/v1
kind: Deployment
metadata:
  name: hono-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hono-api
  template:
    metadata:
      labels:
        app: hono-api
    spec:
      containers:
      - name: hono-api
        image: froghunt3r/hono-api:latest
        ports:
        - containerPort: 9999
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
